# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ccantale <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/02/01 17:10:53 by ccantale          #+#    #+#              #
#    Updated: 2023/02/05 19:07:36 by ccantale         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	g++ -Wall -Wextra -Werror -std=c++98 converter.cpp -o converter

clean:
	rm converter

fclean: clean
