# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ccantale <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/02/01 17:10:44 by ccantale          #+#    #+#              #
#    Updated: 2023/02/05 19:08:01 by ccantale         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	g++ -Wall -Wextra -Werror -std=c++98 main.cpp serialize.cpp -o serializer

clean:
	rm serializer

fclean: clean
